### ISSUE TITLE
Dear Sir,

### ISSUE THREAD

**Issue by PeterChen2018** [Duthomhas/WinBGIm-fixed-sort-of-#1]
I am much appreciate your code. It help me a lot.
Thank you so much !
I live in Taipei city, Taiwan.
Thank you again !

**Comment by Duthomhas** [comment]
You are welcome!

Remember, though, I did not write nor do I maintain WinBGIm. This is explained in the documentation. I just fixed it to compile with modern GCC versions.

(At some future date I will write a BGI for modern 64-bit compilers, but until then...)
